spring:
  autoconfigure.exclude: |
    org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration,
    org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration,
    org.springframework.ai.autoconfigure.vectorstore.redis.RedisVectorStoreAutoConfiguration
  ai:
    openai:
      chat:
        options:
          temperature: 1.0
      image:
        enabled: false # not working at the moment
        # api-key: <Stable diffusion API key>
        # options:
        #   model: stable-diffusion-v1-6
    vectorstore:
      pgvector:
        initialize-schema: true
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
server.tomcat.max-swallow-size: -1

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web.servlet: DEBUG

app:
  always-available-ingredients: wine,salt,pepper,olive oil,broth,rice
  available-ingredients-in-fridge: bacon,onions
